#!/usr/bin/env bash

# Install ufw firewall
apt-get update
apt-get install -y ufw

# Set default firewall policies
ufw default deny incoming
ufw default allow outgoing

# Allow incoming traffic on required ports
ufw allow ssh
ufw allow http
ufw allow https

# Enable firewall
ufw --force enable

# Display firewall status
ufw status
